### ISSUE TITLE
arduino ide not compiling

### ISSUE THREAD

**Issue by andreaguiar** [jeffeb3/esp8266_lights#2]
so I get this errors:

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:89:32: warning: character constant too long for its type [enabled by default]

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:112:32: warning: multi-character character constant [-Wmultichar]

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino: In function 'void loop()':

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:89:39: warning: large integer implicitly truncated to unsigned type [-Woverflow]

esp8266_lights:99: error: 'convertToInt' was not declared in this scope

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:112:38: warning: large integer implicitly truncated to unsigned type [-Woverflow]

esp8266_lights:122: error: 'convertToInt' was not declared in this scope

exit status 1
'convertToInt' was not declared in this scope

**Comment by jeffeb3** [comment]
Put this in the category of "how did this ever work"? convertToInt is in the .ino file, but at the bottom, and I think arduino is doing something magic for me, by defining it early, but you're not getting the same magic.

**Comment by andreaguiar** [comment]
no magic for me? :(

**Comment by jeffeb3** [comment]
Try it with that change. I just added one line, on line 5. I declared the function early.

**Comment by andreaguiar** [comment]
well it did compile in the end but it shows some warnings while compiling:

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:89:32: warning: character constant too long for its type [enabled by default]

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:112:32: warning: multi-character character constant [-Wmultichar]

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino: In function 'void loop()':

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:89:39: warning: large integer implicitly truncated to unsigned type [-Woverflow]

C:\Users\AndrÃ©\Documents\Arduino\esp8266_lights\esp8266_lights.ino:112:38: warning: large integer implicitly truncated to unsigned type [-Woverflow]

Sketch uses 217,666 bytes (50%) of program storage space. Maximum is 434,160 bytes.
Global variables use 34,352 bytes (41%) of dynamic memory, leaving 47,568 bytes for local variables. Maximum is 81,920 bytes.

**Comment by jeffeb3** [comment]
Those are just warnings. Ideally, they would get fixed, but they are not problems.

**Comment by andreaguiar** [comment]
ok thanks

**Comment by andreaguiar** [comment]
So it's working, but I have a question. 
I have this controlling the leds on my pc, the problem I have is each time I wake my pc from sleep, the leds are off. So is there a way to make the controller light up the leds with the last colors before sleep?

**Comment by jeffeb3** [comment]
I don't know how you managed that. The lights only respond to web site requests, and as soon as it's done with the request, it stays at that same value as long as the controller is running. 

Is it possible the controller is being powered off (unplugged) and it just coincides with the computer? Are you using curl? Or a browser? Browsers do funny things in the name of caching.

I used cURL on my Android phone and that worked great, or you could use urllib in python or curl in Linux or cygwin.

**Comment by andreaguiar** [comment]
The controller is powered off when the pc sleeps and I use the browser.

**Comment by jeffeb3** [comment]
"The controller is powered off when the pc sleeps" You mean the green and red lights inside the box go out?

**Comment by jeffeb3** [comment]
And don't test with a browser, it will do funny things, like cache results, and not send a new request to the controller.

**Comment by andreaguiar** [comment]
Yes there is no power when asleep, that's expected, don't want the leds to be on all the time.

I've been looking into ways to save data to flash. Fund the EEPROM.h and the spi_flash.h
Will have to look further into it...

**Comment by jeffeb3** [comment]
Oh, I see. Good luck.
